#ifndef BATTLEFIELD_H
#define BATTLEFIELD_H

#include "common.h"

/* Fills the 5-element array with the fixed data from Table 1 of the spec
   (type name, gun name, impact power, angle range). This data never
   changes between simulations - it's the "rulebook" for each type. */
void initEscortSpecs(EscortSpec specs[5]);

/* Returns a random double between min and max (inclusive-ish).
   Used everywhere we need a "randomly generated" value per the spec. */
double randDouble(double min, double max);

/* Creates one escort ship:
   - picks a random type (A-E)
   - places it at a random (x,y) within the DxD canvas
   - fills in velocity range and angle range following the Table 1 rules
   - assigns the given unique id                                       */
void generateEscortShip(EscortShip *e, int id, double D, double vMaxB,
                         EscortSpec specs[5]);

/* Sets up the battleship: given notation, position (x,y) and vMax
   (all can come from user input or be randomly generated by the
   caller before this is called).                                     */
void initBattleship(Battleship *b, char notation, double x, double y,
                     double vMax);

/* Debug/testing helper - prints an escort ship's details to the screen */
void printEscortShip(EscortShip *e, EscortSpec specs[5]);

/* Debug/testing helper - prints the battleship's details to the screen */
void printBattleship(Battleship *b);

#endif
